/*
    ====================================================================================
    PostgreSQL Review - Template Header

    Purpose: Collect PostgreSQL system introduction information.

    This header collects:
        - PostgreSQL server and cluster identity
        - PostgreSQL version and build information
        - PostgreSQL distribution/flavor best-effort detection
        - Execution context
        - Basic host information visible from PostgreSQL
        - Important PostgreSQL configuration values
        - Databases list
        - Tablespaces list
        - Installed extensions
        - Current database statistics snapshot
        - Current activity summary
        - Replication / recovery high-level state
        - PostgreSQL licensing note
        - Header collection errors, if any

    Important:
        This file should be included at the beginning of the generated script: PostgreSQL_Review_Full_Check_Script.sql

    Expected flow:
        Template_Header.sql
        SQLChecks\*.sql
        Template_Footer.sql

    Output:
        This header does not return the final Review output.
        Final JSON output is generated by Template_Footer.sql.

    Important PostgreSQL limitation:
        PostgreSQL does not expose full operating system and hardware inventory through standard SQL.

        The following information is usually not available from SQL alone:
            - Number of sockets
            - Cores per socket
            - Total physical memory
            - NUMA layout
            - Virtualization type
            - Detailed operating system version

        These values should be collected from the OS, cloud provider, VM platform,
        monitoring platform, or customer documentation when required.

    PostgreSQL documentation:
        https://www.postgresql.org/docs/current/

    System information functions:
        https://www.postgresql.org/docs/current/functions-info.html

    Monitoring statistics:
        https://www.postgresql.org/docs/current/monitoring-stats.html

    Server configuration:
        https://www.postgresql.org/docs/current/runtime-config.html

    System catalogs:
        https://www.postgresql.org/docs/current/catalogs.html
    ====================================================================================
*/


/*
    ====================================================================================
    Header section 1 - Cleanup previous temporary objects
    Purpose: Drop temporary tables from a previous execution in the same session.
             Allows this script to be re-run in the same session, for example from pgAdmin.
    ====================================================================================
*/

    DROP TABLE IF EXISTS pg_review_header_server_identity;
    DROP TABLE IF EXISTS pg_review_header_host_visibility;
    DROP TABLE IF EXISTS pg_review_header_execution_context;
    DROP TABLE IF EXISTS pg_review_header_distribution_detection;
    DROP TABLE IF EXISTS pg_review_header_important_settings;
    DROP TABLE IF EXISTS pg_review_header_licensing;
    DROP TABLE IF EXISTS pg_review_header_databases;
    DROP TABLE IF EXISTS pg_review_header_current_database_session;
    DROP TABLE IF EXISTS pg_review_header_tablespaces;
    DROP TABLE IF EXISTS pg_review_header_extensions;
    DROP TABLE IF EXISTS pg_review_header_database_statistics;
    DROP TABLE IF EXISTS pg_review_header_activity_summary;
    DROP TABLE IF EXISTS pg_review_header_replication_state;
    DROP TABLE IF EXISTS pg_review_header_capabilities;
    DROP TABLE IF EXISTS pg_review_header_errors;
    DROP TABLE IF EXISTS pg_review_results;
    DROP TABLE IF EXISTS pg_review_errors;

/*
    ====================================================================================
    Header section 2 - Create output tables
    Purpose: Create all output tables before collecting data.
    Why: If a specific collection section fails, the relevant table still exists and the final SELECT statements will not fail.
    ====================================================================================
*/

    -- Temp table for Header collection errors
    CREATE TEMP TABLE pg_review_header_errors
    (
        SectionName      text,
        ErrorMessage     text,
        ErrorTime        timestamptz DEFAULT now()
    );

    -- Temp table for PostgreSQL server and cluster identity information
    CREATE TEMP TABLE pg_review_header_server_identity
    (
        PostgreSQLClusterName       text,
        CurrentDatabaseName         text,
        PostgreSQLVersion           text,
        PostgreSQLVersionNum        text,
        PostgreSQLFullVersionString text,
        ServerIPAddress             text,
        ServerPort                  integer,
        PostgreSQLStartTime         timestamptz,
        PostgreSQLUptime            interval,
        IsInRecovery                boolean,
        TransactionReadOnly         text,
        DataDirectory               text,
        ConfigFile                  text,
        HbaFile                     text,
        IdentFile                   text
    );

    -- Temp table for host and operating system information visible from PostgreSQL
    CREATE TEMP TABLE pg_review_header_host_visibility
    (
        ServerIPAddress                 text,
        ServerPort                      integer,
        ClientIPAddress                 text,
        ClientPort                      integer,
        PostgreSQLBuildAndHostString    text,
        OperatingSystemName             text,
        OperatingSystemRelease          text,
        OperatingSystemArchitecture     text,
        VirtualizationType              text,
        NumOfSockets                    integer,
        CoresPerSocket                  integer,
        HostNumOfCores                  integer,
        NumOfNUMAs                      integer,
        PhysicalMemory_GB               numeric,
        HostResourceCollectionNote      text
    );

    -- Temp table for the Review execution context and current user permissions
    CREATE TEMP TABLE pg_review_header_execution_context
    (
        CurrentUser                     text,
        SessionUser                     text,
        CurrentDatabaseName             text,
        CanLogin                        boolean,
        IsSuperuser                     boolean,
        CanCreateDatabase               boolean,
        CanCreateRole                   boolean,
        HasReplicationPrivilege         boolean,
        CanBypassRowLevelSecurity       boolean,
        HasPgMonitor                    boolean,
        HasPgReadAllStats               boolean,
        HasPgReadAllSettings            boolean,
        HasPgStatScanTables             boolean
    );

    -- Temp table for PostgreSQL distribution and managed-service detection
    CREATE TEMP TABLE pg_review_header_distribution_detection
    (
        PostgreSQLDistributionFlavor        text,
        DetectionConfidence                 text,
        PostgreSQLVersion                   text,
        PostgreSQLVersionNum                text,
        HasRdsAdminRole                     boolean,
        HasRdsAdminDatabase                 boolean,
        RdsExtensionsSettingExists          boolean,
        HasRdsToolsExtension                boolean,
        HasAwsCommonsExtension              boolean,
        HasAwsS3Extension                   boolean,
        HasAzurePgAdminRole                 boolean,
        AzureExtensionsSettingExists        boolean,
        HasAzureStorageExtension            boolean,
        HasCloudSqlSuperuserRole            boolean,
        CloudSqlPglogicalSettingExists      boolean,
        HasGoogleMlIntegrationExtension     boolean,
        EdbRedwoodDateSettingExists         boolean,
        HasPgStatStatementsExtension        boolean,
        DetectionNote                       text
    );

    -- Temp table for important PostgreSQL configuration settings
    CREATE TEMP TABLE pg_review_header_important_settings
    (
        SettingName         text,
        SettingValue        text,
        Unit                text,
        Category            text,
        Description         text,
        Context             text,
        ValueType           text,
        BootValue           text,
        ResetValue          text,
        Source              text,
        PendingRestart      boolean
    );

    -- Temp table for PostgreSQL licensing information
    CREATE TEMP TABLE pg_review_header_licensing
    (
        LicensingCategory       text,
        LicensingInformation    text,
        LicensingNote           text
    );

    -- Temp table for the PostgreSQL databases list
    CREATE TEMP TABLE pg_review_header_databases
    (
        DatabaseName        text,
        OwnerName           text,
        AllowConnections    boolean,
        IsTemplate          boolean,
        ConnectionLimit     integer,
        DatabaseEncoding    text,
        DatabaseCollation   text,
        DatabaseCType       text,
        DatabaseSize        text,
        DatabaseSizeBytes   bigint
    );

    -- Temp table for current database session settings
    CREATE TEMP TABLE pg_review_header_current_database_session
    (
        DatabaseName                        text,
        ClientEncoding                      text,
        ServerEncoding                      text,
        DateStyle                           text,
        TimeZone                            text,
        IntervalStyle                       text,
        StandardConformingStrings           text,
        DefaultTransactionIsolation         text,
        CurrentTransactionIsolation         text,
        TransactionReadOnly                 text,
        StatementTimeout                    text,
        LockTimeout                         text,
        IdleInTransactionSessionTimeout     text,
        SearchPath                          text
    );

    -- Temp table for PostgreSQL tablespaces information
    CREATE TEMP TABLE pg_review_header_tablespaces
    (
        TablespaceName          text,
        OwnerName               text,
        TablespaceLocation      text,
        TablespaceOptions       text[]
    );

    -- Temp table for installed extensions in the current database
    CREATE TEMP TABLE pg_review_header_extensions
    (
        ExtensionName       text,
        ExtensionVersion    text,
        SchemaName          text,
        IsRelocatable       boolean
    );

    -- Temp table for current database statistics snapshot
    CREATE TEMP TABLE pg_review_header_database_statistics
    (
        DatabaseName                text,
        CurrentBackends             integer,
        TransactionsCommitted       bigint,
        TransactionsRolledBack      bigint,
        BlocksReadFromDisk          bigint,
        BlocksHitInCache            bigint,
        CacheHitPercent             numeric,
        TuplesReturned              bigint,
        TuplesFetched               bigint,
        TuplesInserted              bigint,
        TuplesUpdated               bigint,
        TuplesDeleted               bigint,
        Conflicts                   bigint,
        TempFiles                   bigint,
        TempBytes                   text,
        TempBytesRaw                bigint,
        Deadlocks                   bigint,
        BlockReadTimeMs             double precision,
        BlockWriteTimeMs            double precision,
        StatisticsResetTime         timestamptz
    );

    -- Temp table for current PostgreSQL activity summary
    CREATE TEMP TABLE pg_review_header_activity_summary
    (
        TotalConnections                    bigint,
        ActiveConnections                   bigint,
        IdleConnections                     bigint,
        IdleInTransactionConnections        bigint,
        SessionsWaitingOnLocks              bigint,
        DistinctUsers                       bigint,
        DistinctApplications                bigint,
        DistinctClientAddresses             bigint,
        OldestBackendStart                  timestamptz,
        OldestTransactionStart              timestamptz,
        OldestQueryStart                    timestamptz
    );

    -- Temp table for replication and recovery state summary
    CREATE TEMP TABLE pg_review_header_replication_state
    (
        IsInRecovery                    boolean,
        WalLevel                        text,
        ArchiveMode                     text,
        MaxWalSenders                   text,
        MaxReplicationSlots             text,
        WalKeepSize                     text,
        ConnectedStandbyCount           bigint,
        ReplicationSlotCount            bigint,
        ActiveReplicationSlotCount      bigint
    );

    -- Temp table for optional PostgreSQL capabilities and feature availability
    CREATE TEMP TABLE pg_review_header_capabilities
    (
        CapabilityName      text,
        IsAvailable         boolean
    );

    -- Temp table for PostgreSQL Review check results
    CREATE TEMP TABLE pg_review_results
    (
        CheckId                 integer PRIMARY KEY,
        Title                   text NOT NULL,
        Category                text NOT NULL,
        Scope                   text NOT NULL,
        RequiresAttention       boolean NOT NULL,
        WorstCaseImpact         integer NOT NULL,
        CurrentStateImpact      integer NOT NULL,
        RecommendationEffort    integer NOT NULL,
        RecommendationRisk      integer NOT NULL,
        Recommendation          text NOT NULL,
        AdditionalInfo          jsonb NOT NULL DEFAULT '{}'::jsonb,
        ResponsibleDbaTeam      text NOT NULL DEFAULT 'Production/Development'
    );

    -- Temp table for PostgreSQL Review check execution errors.
    CREATE TEMP TABLE pg_review_errors
    (
        CheckId             integer,
        Title               text,
        ErrorSqlState       text,
        ErrorMessage        text,
        ErrorDetail         text,
        ErrorHint           text,
        ErrorContext        text,
        IsDeadlockRetry     boolean DEFAULT false,
        ErrorTime           timestamptz DEFAULT now()
    );

/*
    ====================================================================================
    Header section 3 - PostgreSQL Server / Cluster Identity
    Purpose: Basic PostgreSQL identity information.
    Notes: PostgreSQL cluster can contain multiple databases.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_server_identity
    SELECT
        COALESCE(NULLIF(current_setting('cluster_name', true), ''), 'Not provided') AS PostgreSQLClusterName,
        current_database() AS CurrentDatabaseName,
        current_setting('server_version', true) AS PostgreSQLVersion,
        current_setting('server_version_num', true) AS PostgreSQLVersionNum,
        version() AS PostgreSQLFullVersionString,
        inet_server_addr()::text AS ServerIPAddress,
        inet_server_port() AS ServerPort,
        pg_postmaster_start_time() AS PostgreSQLStartTime,
        now() - pg_postmaster_start_time() AS PostgreSQLUptime,
        pg_is_in_recovery() AS IsInRecovery,
        current_setting('transaction_read_only', true) AS TransactionReadOnly,
        current_setting('data_directory', true) AS DataDirectory,
        current_setting('config_file', true) AS ConfigFile,
        current_setting('hba_file', true) AS HbaFile,
        current_setting('ident_file', true) AS IdentFile;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('PostgreSQL Server / Cluster Identity', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 4 - Host / Operating System Visibility from PostgreSQL
    Purpose: Provide host-related information that is visible from PostgreSQL.
    Important: PostgreSQL does not expose full OS/hardware inventory through standard SQL.
               CPU count, sockets, cores per socket, NUMA, physical memory, and virtualization
               type should be collected from OS/cloud/monitoring tools when needed.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_host_visibility
    SELECT
        inet_server_addr()::text AS ServerIPAddress,
        inet_server_port() AS ServerPort,
        inet_client_addr()::text AS ClientIPAddress,
        inet_client_port() AS ClientPort,
        version() AS PostgreSQLBuildAndHostString,
        'Not available from standard PostgreSQL SQL'::text AS OperatingSystemName,
        'Not available from standard PostgreSQL SQL'::text AS OperatingSystemRelease,
        'Not available from standard PostgreSQL SQL'::text AS OperatingSystemArchitecture,
        'Not available from standard PostgreSQL SQL'::text AS VirtualizationType,
        NULL::integer AS NumOfSockets,
        NULL::integer AS CoresPerSocket,
        NULL::integer AS HostNumOfCores,
        NULL::integer AS NumOfNUMAs,
        NULL::numeric AS PhysicalMemory_GB,
        'Collect OS and hardware details from operating system, cloud provider, VM platform, container platform, or monitoring tool.'::text AS HostResourceCollectionNote;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Host / Operating System Visibility from PostgreSQL', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 5 - Execution Context
    Purpose: Identify who executed the Review and what privileges are visible.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_execution_context
    SELECT
        current_user AS CurrentUser,
        session_user AS SessionUser,
        current_database() AS CurrentDatabaseName,
        r.rolcanlogin AS CanLogin,
        r.rolsuper AS IsSuperuser,
        r.rolcreatedb AS CanCreateDatabase,
        r.rolcreaterole AS CanCreateRole,
        r.rolreplication AS HasReplicationPrivilege,
        r.rolbypassrls AS CanBypassRowLevelSecurity,
        pg_has_role(current_user, 'pg_monitor', 'member') AS HasPgMonitor,
        pg_has_role(current_user, 'pg_read_all_stats', 'member') AS HasPgReadAllStats,
        pg_has_role(current_user, 'pg_read_all_settings', 'member') AS HasPgReadAllSettings,
        pg_has_role(current_user, 'pg_stat_scan_tables', 'member') AS HasPgStatScanTables
    FROM pg_roles r
    WHERE r.rolname = current_user;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Execution Context', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 6 - PostgreSQL Distribution / Flavor Detection
    Purpose: Best-effort detection of PostgreSQL distribution/flavor.
    Detects signals for:
                    - Community PostgreSQL or unknown
                    - Amazon RDS for PostgreSQL / Amazon Aurora PostgreSQL
                    - Azure Database for PostgreSQL
                    - Google Cloud SQL for PostgreSQL
                    - EDB Postgres Advanced Server
    Important:
                This is best-effort detection from SQL only.
                Managed services may hide internal details.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_distribution_detection
    WITH settings AS
    (
        SELECT
            current_setting('server_version', true) AS server_version,
            current_setting('server_version_num', true) AS server_version_num,
            current_setting('rds.extensions', true) AS rds_extensions,
            current_setting('azure.extensions', true) AS azure_extensions,
            current_setting('cloudsql.enable_pglogical', true) AS cloudsql_enable_pglogical,
            current_setting('edb_redwood_date', true) AS edb_redwood_date
    ),
    extensions AS
    (
        SELECT
            bool_or(extname = 'rds_tools') AS has_rds_tools,
            bool_or(extname = 'aws_commons') AS has_aws_commons,
            bool_or(extname = 'aws_s3') AS has_aws_s3,
            bool_or(extname = 'azure_storage') AS has_azure_storage,
            bool_or(extname = 'google_ml_integration') AS has_google_ml_integration,
            bool_or(extname = 'pg_stat_statements') AS has_pg_stat_statements
        FROM pg_extension
    ),
    roles AS
    (
        SELECT
            bool_or(rolname = 'rdsadmin') AS has_rdsadmin_role,
            bool_or(rolname = 'azure_pg_admin') AS has_azure_pg_admin_role,
            bool_or(rolname = 'cloudsqlsuperuser') AS has_cloudsqlsuperuser_role
        FROM pg_roles
    ),
    databases AS
    (
        SELECT
            bool_or(datname = 'rdsadmin') AS has_rdsadmin_database
        FROM pg_database
    )
    SELECT
        CASE
            WHEN settings.server_version ILIKE '%EnterpriseDB%'
              OR settings.server_version ILIKE '%EDB%'
              OR settings.edb_redwood_date IS NOT NULL
            THEN 'EDB Postgres Advanced Server'

            WHEN roles.has_rdsadmin_role
              OR databases.has_rdsadmin_database
              OR settings.rds_extensions IS NOT NULL
              OR extensions.has_rds_tools
              OR extensions.has_aws_commons
              OR extensions.has_aws_s3
            THEN
                CASE
                    WHEN settings.server_version ILIKE '%aurora%'
                    THEN 'Amazon Aurora PostgreSQL'
                    ELSE 'Amazon RDS for PostgreSQL or Amazon Aurora PostgreSQL'
                END

            WHEN roles.has_azure_pg_admin_role
              OR settings.azure_extensions IS NOT NULL
              OR extensions.has_azure_storage
            THEN 'Azure Database for PostgreSQL'

            WHEN roles.has_cloudsqlsuperuser_role
              OR settings.cloudsql_enable_pglogical IS NOT NULL
              OR extensions.has_google_ml_integration
            THEN 'Google Cloud SQL for PostgreSQL'

            ELSE 'PostgreSQL Community or unknown distribution'
        END AS PostgreSQLDistributionFlavor,

        CASE
            WHEN settings.server_version ILIKE '%EnterpriseDB%'
              OR settings.server_version ILIKE '%EDB%'
              OR settings.edb_redwood_date IS NOT NULL
              OR roles.has_rdsadmin_role
              OR databases.has_rdsadmin_database
              OR roles.has_azure_pg_admin_role
              OR roles.has_cloudsqlsuperuser_role
            THEN 'High'

            WHEN settings.rds_extensions IS NOT NULL
              OR settings.azure_extensions IS NOT NULL
              OR settings.cloudsql_enable_pglogical IS NOT NULL
              OR extensions.has_rds_tools
              OR extensions.has_aws_commons
              OR extensions.has_aws_s3
              OR extensions.has_azure_storage
              OR extensions.has_google_ml_integration
            THEN 'Medium'

            ELSE 'Best-effort detection'
        END AS DetectionConfidence,

        settings.server_version AS PostgreSQLVersion,
        settings.server_version_num AS PostgreSQLVersionNum,

        COALESCE(roles.has_rdsadmin_role, false) AS HasRdsAdminRole,
        COALESCE(databases.has_rdsadmin_database, false) AS HasRdsAdminDatabase,
        settings.rds_extensions IS NOT NULL AS RdsExtensionsSettingExists,
        COALESCE(extensions.has_rds_tools, false) AS HasRdsToolsExtension,
        COALESCE(extensions.has_aws_commons, false) AS HasAwsCommonsExtension,
        COALESCE(extensions.has_aws_s3, false) AS HasAwsS3Extension,

        COALESCE(roles.has_azure_pg_admin_role, false) AS HasAzurePgAdminRole,
        settings.azure_extensions IS NOT NULL AS AzureExtensionsSettingExists,
        COALESCE(extensions.has_azure_storage, false) AS HasAzureStorageExtension,

        COALESCE(roles.has_cloudsqlsuperuser_role, false) AS HasCloudSqlSuperuserRole,
        settings.cloudsql_enable_pglogical IS NOT NULL AS CloudSqlPglogicalSettingExists,
        COALESCE(extensions.has_google_ml_integration, false) AS HasGoogleMlIntegrationExtension,

        settings.edb_redwood_date IS NOT NULL AS EdbRedwoodDateSettingExists,
        COALESCE(extensions.has_pg_stat_statements, false) AS HasPgStatStatementsExtension,

        'Best-effort detection from SQL only. Validate with customer/provider documentation when required.'::text AS DetectionNote
    FROM settings
    CROSS JOIN extensions
    CROSS JOIN roles
    CROSS JOIN databases;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('PostgreSQL Distribution / Flavor Detection', SQLERRM);
END $$;


/*  
    ====================================================================================
    Header section 7 - Important PostgreSQL Configuration Values
    Purpose: Collect important PostgreSQL settings for system introduction.
             Values are shown for context only.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_important_settings
    SELECT
        name AS SettingName,
        setting AS SettingValue,
        unit AS Unit,
        category AS Category,
        short_desc AS Description,
        context AS Context,
        vartype AS ValueType,
        boot_val AS BootValue,
        reset_val AS ResetValue,
        source AS Source,
        pending_restart AS PendingRestart
    FROM pg_settings
    WHERE name IN
    (
        'max_connections',
        'superuser_reserved_connections',
        'reserved_connections',

        'shared_buffers',
        'effective_cache_size',
        'work_mem',
        'maintenance_work_mem',
        'autovacuum_work_mem',

        'autovacuum',
        'autovacuum_max_workers',
        'autovacuum_naptime',
        'autovacuum_vacuum_threshold',
        'autovacuum_vacuum_scale_factor',
        'autovacuum_analyze_threshold',
        'autovacuum_analyze_scale_factor',
        'autovacuum_freeze_max_age',

        'checkpoint_timeout',
        'checkpoint_completion_target',
        'max_wal_size',
        'min_wal_size',
        'wal_level',
        'wal_compression',
        'archive_mode',
        'archive_command',
        'archive_library',
        'max_wal_senders',
        'max_replication_slots',
        'wal_keep_size',

        'shared_preload_libraries',
        'track_activities',
        'track_counts',
        'track_io_timing',
        'track_wal_io_timing',

        'log_min_duration_statement',
        'log_temp_files',
        'log_autovacuum_min_duration',
        'log_checkpoints',
        'log_lock_waits',
        'deadlock_timeout',

        'max_worker_processes',
        'max_parallel_workers',
        'max_parallel_workers_per_gather',

        'statement_timeout',
        'lock_timeout',
        'idle_in_transaction_session_timeout',
        'temp_file_limit',

        'default_statistics_target',
        'random_page_cost',
        'seq_page_cost',
        'effective_io_concurrency'
    )
    ORDER BY category, name;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Important PostgreSQL Configuration Values', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 8 - PostgreSQL Licensing Information
    Purpose: Provide licensing context.
    Notes: PostgreSQL Community Edition is open-source and does not have per-core licensing limits.
           Managed services and commercial distributions may have provider-specific pricing or subscription models.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_licensing
    SELECT
        'PostgreSQL License'::text AS LicensingCategory,
        'PostgreSQL is released under the PostgreSQL License, a liberal open-source license.'::text AS LicensingInformation,
        'PostgreSQL Community does not use socket/core licensing. Managed services and commercial distributions may have provider-specific pricing or subscriptions.'::text AS LicensingNote;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('PostgreSQL Licensing Information', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 9 - Databases List
    Purpose: List databases in the PostgreSQL cluster.
    Notes: PostgreSQL has multiple databases inside a cluster.
           Object-level checks usually apply only to the database where the script runs.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_databases
    SELECT
        d.datname::text AS DatabaseName,
        pg_get_userbyid(d.datdba)::text AS OwnerName,
        d.datallowconn AS AllowConnections,
        d.datistemplate AS IsTemplate,
        d.datconnlimit AS ConnectionLimit,
        pg_encoding_to_char(d.encoding)::text AS DatabaseEncoding,
        d.datcollate::text AS DatabaseCollation,
        d.datctype::text AS DatabaseCType,
        CASE
            WHEN d.datallowconn THEN pg_size_pretty(pg_database_size(d.datname))
            ELSE NULL
        END AS DatabaseSize,
        CASE
            WHEN d.datallowconn THEN pg_database_size(d.datname)
            ELSE NULL
        END AS DatabaseSizeBytes
    FROM pg_database d
    ORDER BY d.datistemplate, d.datname;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Databases List', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 10 - Current Database Session Defaults
    Purpose: Show session/default values relevant to the current database connection.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_current_database_session
    SELECT
        current_database() AS DatabaseName,
        current_setting('client_encoding', true) AS ClientEncoding,
        current_setting('server_encoding', true) AS ServerEncoding,
        current_setting('DateStyle', true) AS DateStyle,
        current_setting('TimeZone', true) AS TimeZone,
        current_setting('IntervalStyle', true) AS IntervalStyle,
        current_setting('standard_conforming_strings', true) AS StandardConformingStrings,
        current_setting('default_transaction_isolation', true) AS DefaultTransactionIsolation,
        current_setting('transaction_isolation', true) AS CurrentTransactionIsolation,
        current_setting('transaction_read_only', true) AS TransactionReadOnly,
        current_setting('statement_timeout', true) AS StatementTimeout,
        current_setting('lock_timeout', true) AS LockTimeout,
        current_setting('idle_in_transaction_session_timeout', true) AS IdleInTransactionSessionTimeout,
        current_setting('search_path', true) AS SearchPath;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Current Database Session Defaults', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 11 - Tablespaces
    Purpose: List PostgreSQL tablespaces.
    Notes: PostgreSQL tablespaces represent locations in the filesystem.
           Filesystem free space is not available through standard SQL.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_tablespaces
    SELECT
        t.spcname::text AS TablespaceName,
        pg_get_userbyid(t.spcowner)::text AS OwnerName,
        pg_tablespace_location(t.oid)::text AS TablespaceLocation,
        t.spcoptions AS TablespaceOptions
    FROM pg_tablespace t
    ORDER BY t.spcname;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Tablespaces', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 12 - Installed Extensions in Current Database
    Purpose: List extensions installed in the current database.
    Notes: Extensions are database-level in PostgreSQL.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_extensions
    SELECT
        e.extname::text AS ExtensionName,
        e.extversion::text AS ExtensionVersion,
        n.nspname::text AS SchemaName,
        e.extrelocatable AS IsRelocatable
    FROM pg_extension e
    JOIN pg_namespace n
        ON n.oid = e.extnamespace
    ORDER BY e.extname;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Installed Extensions in Current Database', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 13 - Current Database Statistics Snapshot
    Purpose: Show high-level statistics for the current database.
    Notes: These counters are cumulative since statistics reset.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_database_statistics
    SELECT
        datname::text AS DatabaseName,
        numbackends AS CurrentBackends,
        xact_commit AS TransactionsCommitted,
        xact_rollback AS TransactionsRolledBack,
        blks_read AS BlocksReadFromDisk,
        blks_hit AS BlocksHitInCache,
        CASE
            WHEN blks_hit + blks_read > 0
            THEN round((blks_hit::numeric / (blks_hit + blks_read)) * 100, 2)
            ELSE NULL
        END AS CacheHitPercent,
        tup_returned AS TuplesReturned,
        tup_fetched AS TuplesFetched,
        tup_inserted AS TuplesInserted,
        tup_updated AS TuplesUpdated,
        tup_deleted AS TuplesDeleted,
        conflicts AS Conflicts,
        temp_files AS TempFiles,
        pg_size_pretty(temp_bytes) AS TempBytes,
        temp_bytes AS TempBytesRaw,
        deadlocks AS Deadlocks,
        blk_read_time AS BlockReadTimeMs,
        blk_write_time AS BlockWriteTimeMs,
        stats_reset AS StatisticsResetTime
    FROM pg_stat_database
    WHERE datname = current_database();

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Current Database Statistics Snapshot', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 14 - Activity Summary
    Purpose: Provide high-level current connection/session summary.
    Notes: This is a runtime snapshot.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_activity_summary
    SELECT
        count(*) AS TotalConnections,
        count(*) FILTER (WHERE state = 'active') AS ActiveConnections,
        count(*) FILTER (WHERE state = 'idle') AS IdleConnections,
        count(*) FILTER (WHERE state = 'idle in transaction') AS IdleInTransactionConnections,
        count(*) FILTER (WHERE wait_event_type = 'Lock') AS SessionsWaitingOnLocks,
        count(DISTINCT usename) AS DistinctUsers,
        count(DISTINCT application_name) AS DistinctApplications,
        count(DISTINCT client_addr) AS DistinctClientAddresses,
        min(backend_start) AS OldestBackendStart,
        min(xact_start) FILTER (WHERE xact_start IS NOT NULL) AS OldestTransactionStart,
        min(query_start) FILTER (WHERE query_start IS NOT NULL) AS OldestQueryStart
    FROM pg_stat_activity;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Activity Summary', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 15 - Replication and Recovery State
    Purpose: Provide high-level replication/recovery information.
    Notes: This is not a replication health check.
           It is only system introduction information.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_replication_state
    SELECT
        pg_is_in_recovery() AS IsInRecovery,
        current_setting('wal_level', true) AS WalLevel,
        current_setting('archive_mode', true) AS ArchiveMode,
        current_setting('max_wal_senders', true) AS MaxWalSenders,
        current_setting('max_replication_slots', true) AS MaxReplicationSlots,
        current_setting('wal_keep_size', true) AS WalKeepSize,
        (
            SELECT count(*)
            FROM pg_stat_replication
        ) AS ConnectedStandbyCount,
        (
            SELECT count(*)
            FROM pg_replication_slots
        ) AS ReplicationSlotCount,
        (
            SELECT count(*)
            FROM pg_replication_slots
            WHERE active
        ) AS ActiveReplicationSlotCount;

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Replication and Recovery State', SQLERRM);
END $$;


/*
    ====================================================================================
    Header section 16 - Capability Summary
    Purpose: Show which optional PostgreSQL capabilities/views/extensions are available.
             This is useful for understanding what later checks can use.
    ====================================================================================
*/

DO $$
BEGIN
    INSERT INTO pg_review_header_capabilities
    SELECT
        'pg_stat_statements extension installed in current database' AS CapabilityName,
        EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_stat_statements') AS IsAvailable
    UNION ALL
    SELECT
        'pg_stat_statements view visible',
        to_regclass('public.pg_stat_statements') IS NOT NULL
        OR to_regclass('pg_catalog.pg_stat_statements') IS NOT NULL
    UNION ALL
    SELECT
        'pg_stat_checkpointer view available',
        to_regclass('pg_catalog.pg_stat_checkpointer') IS NOT NULL
    UNION ALL
    SELECT
        'pg_stat_io view available',
        to_regclass('pg_catalog.pg_stat_io') IS NOT NULL
    UNION ALL
    SELECT
        'pg_stat_wal view available',
        to_regclass('pg_catalog.pg_stat_wal') IS NOT NULL
    UNION ALL
    SELECT
        'Current user has pg_monitor',
        pg_has_role(current_user, 'pg_monitor', 'member')
    UNION ALL
    SELECT
        'Current user has pg_read_all_stats',
        pg_has_role(current_user, 'pg_read_all_stats', 'member')
    UNION ALL
    SELECT
        'Current user has pg_read_all_settings',
        pg_has_role(current_user, 'pg_read_all_settings', 'member')
    UNION ALL
    SELECT
        'Current database TEMP privilege',
        has_database_privilege(current_user, current_database(), 'TEMP');

EXCEPTION WHEN OTHERS THEN
    INSERT INTO pg_review_header_errors(SectionName, ErrorMessage)
    VALUES ('Capability Summary', SQLERRM);
END $$;

