
/* DESCRIPTION:
   What This Means: log_temp_files is disabled. This prevents PostgreSQL from
   logging temporary file usage generated by queries that spill to disk.

   WHY THIS MATTERS:
   Temporary file creation often indicates insufficient work_mem, inefficient
   query plans, large sorts, hash operations, or reporting workloads. Without
   logging, it can be difficult to identify queries that generate excessive
   temporary I/O and negatively impact performance.

   Recommendations:
   Consider configuring log_temp_files to capture temporary file activity.
   A common starting value is 0 (log all temporary files) or a threshold such
   as 10 MB to reduce logging volume while still identifying significant spills.

   Scope : Cluster-level
   Category : Monitoring

   REFERENCES:
   https://www.postgresql.org/docs/current/runtime-config-logging.html
   https://www.postgresql.org/docs/current/runtime-config-resource.html
*/

v_AdditionalInfo := (
    SELECT CASE
        WHEN current_setting('log_temp_files', true)::integer >= 0
            THEN NULL::jsonb
        ELSE jsonb_build_object(
            'LogTempFiles',
                current_setting('log_temp_files', true),
            'FindingReason',
                'log_temp_files is disabled (-1), so temporary file creation is not being logged.'
        )
    END
);

INSERT INTO pg_review_results (
    CheckId,
    Title,
    Category,
    Scope,
    RequiresAttention,
    WorstCaseImpact,
    CurrentStateImpact,
    RecommendationEffort,
    RecommendationRisk,
    Recommendation,
    AdditionalInfo,
    ResponsibleDbaTeam
)
SELECT
    v_CheckId,
    v_CheckTitle,
    'Observability',
    'Cluster-level',
    CASE WHEN v_AdditionalInfo IS NULL THEN false ELSE true END,
    2,
    CASE WHEN v_AdditionalInfo IS NULL THEN 0 ELSE 1 END,
    CASE WHEN v_AdditionalInfo IS NULL THEN 0 ELSE 1 END,
    CASE WHEN v_AdditionalInfo IS NULL THEN 0 ELSE 1 END,
    CASE
        WHEN v_AdditionalInfo IS NULL
            THEN 'log_temp_files is configured.'
        ELSE
            'Consider enabling log_temp_files to help identify queries that spill to disk and generate excessive temporary I/O.'
    END,
    COALESCE(v_AdditionalInfo, '{}'::jsonb),
    'Production';